version: '2'
services:
    demo-app:
        image: demo
        external_links:
            - demo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/demo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo-postgresql:
        extends:
            file: postgresql.yml
            service: demo-postgresql
