version: '2'
services:
    demo-app:
        image: demo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://demo-mysql:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - APPLICATION_CLUSTER_URI=terracotta://demo-terracotta-server1:9410,demo-terracotta-server2:9410/demo-entity
            - APPLICATION_STUBWEBSERVICES=false
            - APPLICATION_GOOGLEAPIKEY # this value needs to be passed via an environment variable
            - APPLICATION_DARKSKYAPIKEY # this value needs to be passed via an environment variable
            - APPLICATION_BIOGRAPHIESREMOTELOCATION # this value needs to be passed via an environment variable
        ports:
            - 8080
    demo-mysql:
        extends:
            file: mysql.yml
            service: demo-mysql
    demo-terracotta-server1:
        extends:
            file: terracotta-server-ha.yml
            service: demo-terracotta-server1
    demo-terracotta-server2:
        extends:
            file: terracotta-server-ha.yml
            service: demo-terracotta-server2
